name: Build and Release SAD

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build EXE
        run: |
          pyinstaller --noconsole --onefile --icon=icon.ico main.py --name "SAD"

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: SAD-windows
          path: dist/SAD.exe

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/SAD.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
