name: Build Windows EXE (SAD)

on:
  workflow_dispatch: {}
  push:
    tags: ['v*']

jobs:
  build-win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Upgrade pip
        run: python -m pip install -U pip setuptools wheel

      - name: Install deps
        run: |
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build EXE
        run: |
          pyinstaller --noconfirm --clean --onefile ^
            --name SAD ^
            --icon icon.ico ^
            main.py

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: SAD-Windows-EXE
          path: dist/SAD.exe
          if-no-files-found: error
